#include <stdio.h>

int isPalindrome(int x) {
    if (x < 0) {
        return 0;
    }
    if (x % 10 == 0 && x != 0) {
        return 0;
    }

    int reversed = 0, temp = x;

    while (temp > 0) {
        reversed = reversed * 10 + temp % 10;
        temp /= 10;
    }

    return x == reversed;
}

int main() {
    int num;
    printf("Ingrese un numero: ");
    scanf("%d", &num);

    if (isPalindrome(num)) {
        printf("true\n");
    } else {
        printf("false\n");
    }

    return 0;
}
